### ISSUE TITLE
New Location Object

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#117]
#111 I saw this and it looks sexy. However, I am not sure how to implement it. I didn't even realize this was possible. I am 100% supporting you rewriting locations this way. I think we need a location variable that each character has, so when you load your account it tells the game your current location. Whether or not the "town" link appears in the sidebar should be dependent on your location type.

**Comment by klondikemarlen** [comment]
That was the idea. With Classes you can pretty much categorize and extend (use inheritance) anything you can think up. I'll keep working on the implementation.

I'm still not sure whether I should try and keep the HTML/Jinja templating completely separtate or as a display method in the class. Right now I'm leaning towards using a display method for each location class that you can call to make it display the data as HTML using templates. Sadly I haven't worked out how to do that yet .... but that is the other nice thing about Classes ... I just have to accommodate the display function and someone else can write it :)

**Comment by klondikemarlen** [comment]
https://github.com/elthran/flask-game/blob/master/flask-intro/locations.py my work in progress.

**Comment by elthran** [comment]
I understand some of that code :P I can't wait to see it implemented!

**Comment by elthran** [comment]
Well I implemented most of it!! Just waiting for you to tie it in to .txt files :D

**Comment by klondikemarlen** [comment]
Well I want to tie it to spreadsheet files ... like excel or .odt. I don't think it is actually that hard. If I understood Jinja as a templating language that would work too.

**Comment by klondikemarlen** [comment]
I really want to get the new database Class set up before I start a new project but I might use this idea in that too so it would be a good test spec.

**Comment by elthran** [comment]
If you can gt it into an excel type of file, I can go nuts creating dozens of locations and worlds. I can't create quests or stories, or monsters, or NPCs at the moment because the storage of the data is awkard in python currently.

**Comment by klondikemarlen** [comment]
Mount&Blade does this especially TLD. That is why they are so awesome. I researched it. The main thing is to define the data type and format you want before hand and convert it into some kind of python dictionary ... and store the data in a database. We already have a database (mostly) so I think next weekend (in Dawson, I'm going home of the holidays). I will try and build a excel to database to python dict class set (I'll probably need three of them). Do you think you could write down the basic elements that you need stored?
e.g. For map location you need a "name", "connecting locations", "places at the location" and so on. It doesn't have to cover everything but the more it covers the less hard it will be to build again (when it inevitably needs to be rebuild because we missed something important :P). I posted a link about ERD's that had a nice breakdown in it.

**Comment by elthran** [comment]
Yes!!!! Let's create a google document for each data type (charactrs, locations, quests, items, monsters, etc) and brainstorm what we need in each data type.

https://drive.google.com/drive/folders/0B2PTEMx-YNnvM20zVzVSZVZrWWc?usp=sharing

**Comment by klondikemarlen** [comment]
More or less implemented in database v3 branch as of  182f8e8
